- name: Install Jenkins
  hosts: ec2_instances # Same you mentioned in data "template_file" "inventory"
  become: true
  tasks:
  - name: Update the cache
    apt:
      update_cache: yes

  - name: Install curl
    apt:
      name: curl
      state: present

  - name: Install gnupg
      apt:
        name: gnupg
        state: present

  - name: Install java  
    apt:
      name: openjdk-11-jdk
      state: present

  - name: Install Jenkins on Servers
    shell: "curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | sudo tee /usr/share/keyrings/jenkins-keyring.asc"
    args:
      executable: /bin/bash

  - name: Jenkins repository
    shell: sudo sh -c 'echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
    args:
      executable: /bin/bash

  - name: Update the cache
    apt:
      update_cache: yes

  - name: Install Jenkins
    apt:
      name: jenkins
      state: present

  - name: Start jenkins Servers
    service:
      name: jenkins
      state: started
      enabled: yes

  - name: Retrieve jenkins password
    fetch:
      src: /var/lib/jenkins/secrets/initialAdminPassword
      dest: "{{ playbook_dir }}/initialAdminPassword"
      flat: yes
